version: "3.8" # specify docker-compose version

# Define the services/containers to be run
services:
  cook14_angular: # name of the first service
    build: # specify the directory of the Dockerfile
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: cook14_angular
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    ports:
      - "4200:4200" # specify port forewarding
      - "49153:49153"
    environment:
      - NODE_ENV=dev

  cook14_express: #name of the second service
    build: # specify the directory of the Dockerfile
      context: ./api
      dockerfile: Dockerfile.dev
    container_name: cook14_express
    volumes:
      - ./api:/api
      - /api/node_modules
    ports:
      - "5000:5000" #specify ports forewarding
    environment:
      - PORT=5000
    links:
      - cook14_database

  cook14_database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  cook14_adminer:
    image: adminer
    restart: always
    ports:
      - 8040:8080

  cook14_nginx: #name of the fourth service
    build: loadbalancer # specify the directory of the Dockerfile
    container_name: cook14_nginx
    ports:
      - "8046:80" #specify ports forewarding
    links:
      - cook14_express
      - cook14_angular

